[functions.save-pin]
enabled = true
verify_jwt = true
import_map = "./functions/save-pin/deno.json"
entrypoint = "./functions/save-pin/index.ts"

[functions.activate-pin]
enabled = true
verify_jwt = true
import_map = "./functions/activate-pin/deno.json"
entrypoint = "./functions/activate-pin/index.ts"

[functions.deactivate-pin]
enabled = true
verify_jwt = true
import_map = "./functions/deactivate-pin/deno.json"
entrypoint = "./functions/deactivate-pin/index.ts"

[functions.get-active-pins]
enabled = true
verify_jwt = true
import_map = "./functions/get-active-pins/deno.json"
entrypoint = "./functions/get-active-pins/index.ts"

[functions.handle-new-user]
enabled = true
verify_jwt = true
import_map = "./functions/handle-new-user/deno.json"
entrypoint = "./functions/handle-new-user/index.ts"

[functions.handle-redirect]
enabled = true
verify_jwt = false
import_map = "./functions/handle-redirect/deno.json"
entrypoint = "./functions/handle-redirect/index.ts"
